import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import pydeck as pdk
import os

# Set page config for a premium wide layout
st.set_page_config(
    page_title="Smart Traffic Violation Pattern Detector",
    page_icon="🚦",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom premium CSS for dark theme, glassmorphism, and card designs
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap');
    
    /* Global Styles */
    .stApp {
        background-color: #0F172A;
        color: #F8FAFC;
        font-family: 'Outfit', sans-serif;
    }
    
    /* Header styling */
    .main-title {
        font-size: 2.5rem;
        font-weight: 700;
        background: linear-gradient(90deg, #38BDF8, #818CF8);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0.5rem;
        padding-top: 1rem;
    }
    
    .subtitle {
        color: #94A3B8;
        font-size: 1.1rem;
        margin-bottom: 2rem;
    }
    
    /* Metrics Row */
    .metrics-container {
        display: flex;
        gap: 1.5rem;
        margin-bottom: 2rem;
    }
    
    /* Glassmorphism Metric Card */
    .metric-card {
        flex: 1;
        background: rgba(30, 41, 59, 0.65);
        backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.05);
        border-left: 4px solid #38BDF8;
        border-radius: 12px;
        padding: 1.25rem;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
        transition: all 0.3s ease;
    }
    
    .metric-card:hover {
        transform: translateY(-3px);
        box-shadow: 0 8px 25px rgba(56, 189, 248, 0.15);
        border-color: rgba(56, 189, 248, 0.4);
    }
    
    .metric-label {
        font-size: 0.85rem;
        color: #94A3B8;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        margin-bottom: 0.5rem;
        font-weight: 600;
    }
    
    .metric-value {
        font-size: 1.8rem;
        font-weight: 700;
        color: #F8FAFC;
    }
    
    .metric-desc {
        font-size: 0.75rem;
        color: #34D399;
        margin-top: 0.25rem;
        display: flex;
        align-items: center;
        gap: 4px;
    }
    
    /* Sections styling */
    .section-header {
        font-size: 1.4rem;
        font-weight: 600;
        color: #38BDF8;
        border-bottom: 1px solid rgba(56, 189, 248, 0.2);
        padding-bottom: 0.5rem;
        margin-bottom: 1.25rem;
        margin-top: 1.5rem;
    }
</style>
""", unsafe_allow_html=True)

# Helper function to load outputs from files or directories generated by Spark/Pandas
def load_csv_output(path):
    if os.path.isfile(path):
        return pd.read_csv(path)
    elif os.path.isdir(path):
        # Look for part-*.csv first
        csv_files = [f for f in os.listdir(path) if f.startswith('part-') and f.endswith('.csv')]
        if csv_files:
            return pd.read_csv(os.path.join(path, csv_files[0]))
        # Fall back to any csv in directory
        csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
        if csv_files:
            return pd.read_csv(os.path.join(path, csv_files[0]))
    raise FileNotFoundError(f"Could not locate CSV output at {path}")

def load_parquet_output(path):
    if os.path.isfile(path):
        return pd.read_parquet(path)
    elif os.path.isdir(path):
        pq_files = [f for f in os.listdir(path) if f.startswith('part-') and f.endswith('.parquet')]
        if pq_files:
            return pd.read_parquet(os.path.join(path, pq_files[0]))
        pq_files = [f for f in os.listdir(path) if f.endswith('.parquet')]
        if pq_files:
            return pd.read_parquet(os.path.join(path, pq_files[0]))
    raise FileNotFoundError(f"Could not locate Parquet output at {path}")

# Load all aggregated data
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")

try:
    df_time_type = load_csv_output(os.path.join(DATA_DIR, "output", "time_type_aggregation.csv"))
    df_locations = load_csv_output(os.path.join(DATA_DIR, "output", "violations_per_location_csv"))
    df_clusters = load_csv_output(os.path.join(DATA_DIR, "output", "hotspot_clusters_csv"))
    df_hourly = load_parquet_output(os.path.join(DATA_DIR, "aggregations", "per_hour"))
    data_loaded = True
except Exception as e:
    st.error(f"Error loading processed data: {str(e)}")
    st.info("Ensure the data processing pipeline has run successfully by executing `python src/data_cleaning.py` and the aggregation scripts.")
    data_loaded = False

if data_loaded:
    # ------------------ SIDEBAR FILTERS ------------------
    st.sidebar.markdown(
        "<h2 style='color:#38BDF8; font-weight:700;'>Dashboard Filters</h2>", 
        unsafe_allow_html=True
    )
    st.sidebar.markdown("Filter analytics dynamically:")
    
    # Filter by violation type
    all_violations = sorted(df_time_type['Violation_Type'].unique())
    selected_violations = st.sidebar.multiselect(
        "Violation Types",
        options=all_violations,
        default=all_violations
    )
    
    # Filter by Day of Week
    days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    selected_days = st.sidebar.multiselect(
        "Days of the Week",
        options=days_order,
        default=days_order
    )
    
    # Apply filters to dataframes
    df_time_filtered = df_time_type[
        df_time_type['Violation_Type'].isin(selected_violations) & 
        df_time_type['DayOfWeek'].isin(selected_days)
    ]
    
    # ------------------ HEADER SECTION ------------------
    st.markdown("<div class='main-title'>🚦 Smart Traffic Violation Pattern Detector</div>", unsafe_allow_html=True)
    st.markdown("<div class='subtitle'>Interactive analytics, peak frequency patterns, and geospatial hotspot clustering</div>", unsafe_allow_html=True)
    
    # ------------------ METRICS ROW ------------------
    # Calculate key metrics
    total_violations = df_time_filtered['count'].sum() if len(df_time_filtered) > 0 else 0
    
    if len(df_time_filtered) > 0:
        top_type = df_time_filtered.groupby('Violation_Type')['count'].sum().idxmax()
        top_type_val = df_time_filtered.groupby('Violation_Type')['count'].sum().max()
        
        peak_hour = df_time_filtered.groupby('Hour')['count'].sum().idxmax()
        peak_hour_str = f"{peak_hour:02d}:00"
    else:
        top_type = "N/A"
        top_type_val = 0
        peak_hour_str = "N/A"
        
    top_loc = df_locations.iloc[0]['Location'] if len(df_locations) > 0 else "N/A"
    
    # Custom CSS-based metric cards layout
    cols = st.columns(4)
    with cols[0]:
        st.markdown(f"""
        <div class="metric-card" style="border-left-color: #38BDF8;">
            <div class="metric-label">Total Violations</div>
            <div class="metric-value">{total_violations:,}</div>
            <div class="metric-desc">🟢 Live filter metrics active</div>
        </div>
        """, unsafe_allow_html=True)
        
    with cols[1]:
        st.markdown(f"""
        <div class="metric-card" style="border-left-color: #EC4899;">
            <div class="metric-label">Primary Infraction</div>
            <div class="metric-value" style="font-size:1.4rem; padding-top:0.35rem; padding-bottom:0.35rem;">{top_type}</div>
            <div class="metric-desc">🔥 {top_type_val:,} total incidents</div>
        </div>
        """, unsafe_allow_html=True)
        
    with cols[2]:
        st.markdown(f"""
        <div class="metric-card" style="border-left-color: #F59E0B;">
            <div class="metric-label">Peak Traffic Hour</div>
            <div class="metric-value">{peak_hour_str}</div>
            <div class="metric-desc">🕒 Heavy violation rush</div>
        </div>
        """, unsafe_allow_html=True)
        
    with cols[3]:
        st.markdown(f"""
        <div class="metric-card" style="border-left-color: #10B981;">
            <div class="metric-label">Primary Hotspot</div>
            <div class="metric-value" style="font-size:1.15rem; padding-top:0.6rem; padding-bottom:0.6rem;">{top_loc}</div>
            <div class="metric-desc">📍 Most dangerous intersection</div>
        </div>
        """, unsafe_allow_html=True)
        
    # ------------------ GRAPHS SECTION ------------------
    layout_cols = st.columns([1, 1])
    
    with layout_cols[0]:
        st.markdown("<div class='section-header'>⏰ Violation Frequency by Time of Day</div>", unsafe_allow_html=True)
        if len(df_time_filtered) > 0:
            hourly_data = df_time_filtered.groupby('Hour')['count'].sum().reset_index()
            
            # Altair Premium Line Chart
            hourly_chart = alt.Chart(hourly_data).mark_area(
                line={'color': '#38BDF8', 'size': 3},
                color=alt.Gradient(
                    gradient='linear',
                    stops=[alt.GradientStop(color='rgba(56, 189, 248, 0.4)', offset=0),
                           alt.GradientStop(color='rgba(56, 189, 248, 0.0)', offset=1)],
                    x1=1, y1=1, x2=1, y2=0
                )
            ).encode(
                x=alt.X('Hour:Q', title='Hour of the Day (0-23)', scale=alt.Scale(domain=[0, 23])),
                y=alt.Y('count:Q', title='Number of Violations'),
                tooltip=['Hour', 'count']
            ).properties(
                height=320
            ).configure_axis(
                gridColor='rgba(255, 255, 255, 0.05)',
                labelColor='#94A3B8',
                titleColor='#94A3B8',
                domain=False
            ).configure_view(
                strokeWidth=0
            )
            st.altair_chart(hourly_chart, use_container_width=True)
        else:
            st.info("No data available for the selected filters.")
            
    with layout_cols[1]:
        st.markdown("<div class='section-header'>📅 Violation Distribution by Day of Week</div>", unsafe_allow_html=True)
        if len(df_time_filtered) > 0:
            daily_data = df_time_filtered.groupby('DayOfWeek')['count'].sum().reindex(selected_days).reset_index()
            
            # Altair Premium Bar Chart
            daily_chart = alt.Chart(daily_data).mark_bar(
                color='#818CF8',
                cornerRadiusTopLeft=6,
                cornerRadiusTopRight=6
            ).encode(
                x=alt.X('DayOfWeek:N', title='Day of the Week', sort=days_order),
                y=alt.Y('count:Q', title='Number of Violations'),
                tooltip=['DayOfWeek', 'count']
            ).properties(
                height=320
            ).configure_axis(
                gridColor='rgba(255, 255, 255, 0.05)',
                labelColor='#94A3B8',
                titleColor='#94A3B8',
                domain=False
            ).configure_view(
                strokeWidth=0
            )
            st.altair_chart(daily_chart, use_container_width=True)
        else:
            st.info("No data available for the selected filters.")

    # ------------------ MAP & CATEGORY BREAKDOWN ------------------
    layout_cols2 = st.columns([1.25, 0.75])
    
    with layout_cols2[0]:
        st.markdown("<div class='section-header'>🗺️ Machine Learning Clustered Hotspots (KMeans, k=5)</div>", unsafe_allow_html=True)
        
        # Color coding for hotspots on Pydeck map
        cluster_colors = {
            0: [239, 68, 68, 160],   # Red
            1: [59, 130, 246, 160],  # Blue
            2: [16, 185, 129, 160],  # Green
            3: [245, 158, 11, 160],  # Yellow
            4: [139, 92, 246, 160]   # Purple
        }
        
        df_clusters['color'] = df_clusters['prediction'].map(cluster_colors)
        
        # Build Pydeck Scatterplot Layer
        layer = pdk.Layer(
            "ScatterplotLayer",
            df_clusters,
            get_position="[lon, lat]",
            get_color="color",
            get_radius=110,
            pickable=True,
        )
        
        # Define viewport
        view_state = pdk.ViewState(
            latitude=df_clusters['lat'].mean(),
            longitude=df_clusters['lon'].mean(),
            zoom=11.5,
            pitch=40,
        )
        
        # Pydeck Deck
        deck = pdk.Deck(
            map_style="mapbox://styles/mapbox/dark-v9",
            initial_view_state=view_state,
            layers=[layer],
            tooltip={"text": "Violation ID: {violation_id}\nCluster: {prediction}"}
        )
        
        st.pydeck_chart(deck)
        
        # Legend
        st.markdown("""
        <div style="display:flex; gap:1.5rem; justify-content:center; padding-top:0.5rem; font-size:0.85rem; color:#94A3B8;">
            <div><span style="color:#EF4444; font-size:1.1rem;">■</span> Cluster 0</div>
            <div><span style="color:#3B82F6; font-size:1.1rem;">■</span> Cluster 1</div>
            <div><span style="color:#10B981; font-size:1.1rem;">■</span> Cluster 2</div>
            <div><span style="color:#F59E0B; font-size:1.1rem;">■</span> Cluster 3</div>
            <div><span style="color:#8B5CF6; font-size:1.1rem;">■</span> Cluster 4</div>
        </div>
        """, unsafe_allow_html=True)
        
    with layout_cols2[1]:
        st.markdown("<div class='section-header'>📊 Violations by Category</div>", unsafe_allow_html=True)
        if len(df_time_filtered) > 0:
            type_data = df_time_filtered.groupby('Violation_Type')['count'].sum().reset_index()
            type_data = type_data.sort_values(by='count', ascending=True)
            
            # Horizontal Bar Chart
            type_chart = alt.Chart(type_data).mark_bar(
                color='#F43F5E',
                cornerRadiusBottomRight=4,
                cornerRadiusTopRight=4
            ).encode(
                x=alt.X('count:Q', title='Violation Count'),
                y=alt.Y('Violation_Type:N', title='', sort='-x'),
                tooltip=['Violation_Type', 'count']
            ).properties(
                height=350
            ).configure_axis(
                gridColor='rgba(255, 255, 255, 0.05)',
                labelColor='#94A3B8',
                titleColor='#94A3B8',
                domain=False
            ).configure_view(
                strokeWidth=0
            )
            st.altair_chart(type_chart, use_container_width=True)
        else:
            st.info("No data available.")

    # ------------------ RECENT LOGS ------------------
    st.markdown("<div class='section-header'>📋 Sample Violation Record Ingestion logs</div>", unsafe_allow_html=True)
    df_raw_logs = df_clusters[['violation_id', 'lat', 'lon', 'prediction']].rename(
        columns={'prediction': 'cluster_id'}
    ).head(10)
    st.dataframe(df_raw_logs, use_container_width=True)
